### ISSUE TITLE
Not Found AMMID

### ISSUE THREAD

**Issue by taotaolin** [henrytirla/Solana-Raydium-Trading#13]
Thank you for your contribution, but in actual transactions, I found that many tokens will prompt AMMID NOT FOUND SEARCHING WILL BE FETCHING WITH RAYDIUM SDK. In fact, the transaction has been started for a long time. What is the problem? example: 3S8qX1MsMqRbiwKg2cQyx7nis1oHMgaCuc9c4VfvVdPN or  BsjcdsZGq2myoCQEv1v7MMvjfUxkpNoqH6WaXWUzpump  They all execute transactions on Raydium

**Comment by henrytirla** [comment]
Are you snipping new pairs.?

**Comment by taotaolin** [comment]
> Are you snipping new pairs.?

I have tried new pairs and some of the pairs that have already started for a few hours cannot be found

**Comment by henrytirla** [comment]
Working on improving the search data structure, for some reason some tokens are not detected
