### ISSUE TITLE
buy_wrap_sol

### ISSUE THREAD

**Issue by evwyk1** [henrytirla/Solana-Raydium-Trading#19]
Hi. 
This is the response I get from running "buy_wrap_sol"
I am unable to resolve it. Please assist.
"sunghoon" is the token I am trying to buy. I get the same response regardless which Sol Token I try.

(venv) C:\<MyPath>\Solana-Raydium-Trading\WrapSol>python buy_wrap_sol.py
<My wallet address>
Response: sunghoon
Execute Transaction...
Unhandled exception: cannot convert 'Transaction' object to bytes. Retrying...
Response: sunghoon
Execute Transaction...
Unhandled exception: cannot convert 'Transaction' object to bytes. Retrying...
Failed to confirm transaction after maximum retries.

**Comment by henrytirla** [comment]
Repo has been updated this should be fixed.
