### ISSUE TITLE
No method

### ISSUE THREAD

**Issue by javvellim** [henrytirla/Solana-Raydium-Trading#4]
Hi. Why is there a file called buy_WithoutWrapAcc.py are you using _Token Code._create_wrapped_native_account_args ? After all, this contradicts the name of the file.

Still, do you have a code option where the Wrapped WSOL Account is not used? Where the purchase of tokens takes place directly from WSOL. Thanks

**Comment by henrytirla** [comment]
Hey thanks for the feedback for every transaction wrap sol is used so my file name might not be accurate what I meant is buy happens without the buying account sol token account which is in wrap sol. I will do the renaming for more clarity

**Comment by javvellim** [comment]
Thanks for the quick response. I was wondering if you have a ready-made option to purchase new tokens using a balance from an associated WSOL account? Since the creation of _Token Core._create_wrapped_native_account_args and the subsequent closure of CloseAccountParams account lead to the transaction taking longer than if the swap was performed directly from the associated WSOL account

**Comment by henrytirla** [comment]
Yes. I will upload it soon .🚀🚀🚀

**Comment by javvellim** [comment]
> Yes. I will upload it soon .🚀🚀🚀

great. I'll be waiting!

**Comment by henrytirla** [comment]
It's uploaded Jito bundles coming soon
