### ISSUE TITLE
Unhandled exception: string indices must be integers

### ISSUE THREAD

**Issue by Cyberlion2024** [henrytirla/Solana-Raydium-Trading#7]
Good morning, 

could you please tell me how to solve that problem? Unhandled exception: string indices must be integers some times i have this error

Kind regards

**Comment by henrytirla** [comment]
Please give more details which script are you using?

**Comment by Cyberlion2024** [comment]
Thank you for your reply, i am using Solana-Raydium-Trading/Without_WrapSolTokenAccount/buy_WithoutWrapAcc.py and as rpc i am using helius developer plan

Kind regards

**Comment by Cyberlion2024** [comment]
Update: now it says Unhandled exception: Unable to confirm transaction  Retrying...

**Comment by henrytirla** [comment]
Bundling with jito should solve this I would update this later today.
